require:
  - rubocop-rails
  - rubocop-minitest

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Include:
    - '**/*.rb'
  Exclude:
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'script/**/*'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30
